In [18]:
import numpy as np

a = np.arange(3) + 1
a=a.reshape(3,1)
b = np.arange(3) + 1
b=b.reshape(1,3)

print(a,a.shape,b,b.shape)

c = a @ b

print(c)

[[1]
 [2]
 [3]] (3, 1) [[1 2 3]] (1, 3)
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [19]:
a = np.array([[3,3],[3,5]])
b = np.array([[6],[0]])
bt = np.array([[1,1,1],[0,1,2]])
c = bt.T @ np.linalg.inv(a) @ bt @ np.array([[6],[0],[0]])

print(c,np.linalg.matrix_rank(c))

[[ 5.]
 [ 2.]
 [-1.]] 1


In [20]:
x = np.array([[6],[0],[0]])
B = np.array([[1,0],[1,1],[1,2]])
pix = B @ np.linalg.inv(B.T @ B) @ B.T @ x

print(pix,np.linalg.matrix_rank(pix))

[[ 5.]
 [ 2.]
 [-1.]] 1


In [21]:
print(np.linalg.norm(x))

6.0


In [1]:
def solution(laps):
    eliminated = []  # To store the order of eliminated racers
    remaining_racers = set()  # To keep track of eliminated racers
    
    # Process each lap
    for lap in laps:
        # Split each lap into (name, time) pairs
        lap_times = [(entry.split()[0], int(entry.split()[1])) for entry in lap if entry.split()[0] not in remaining_racers]
        
        if not lap_times:
            continue  # If all racers are already eliminated, skip this lap
        
        # Sort by time (highest first) and alphabetically in case of ties
        lap_times.sort(key=lambda x: (-x[1], x[0]))

        # Get the slowest time from the sorted list
        slowest_time = lap_times[0][1]

        # Find all drivers with the slowest time
        slowest_drivers = [driver for driver, time in lap_times if time == slowest_time]
        
        # Sort slowest drivers alphabetically
        slowest_drivers.sort()

        # Add slowest drivers to the elimination list and update the set of eliminated racers
        for driver in slowest_drivers:
            if driver not in remaining_racers:
                eliminated.append(driver)
                remaining_racers.add(driver)

    return eliminated

def solution(laps):
    eliminated = []  # To store the order of eliminated racers
    remaining_racers = set()  # To keep track of eliminated racers
    
    # Process each lap
    for lap in laps:
        # Split each lap into (name, time) pairs
        lap_times = [(entry.split()[0], int(entry.split()[1])) for entry in lap if entry.split()[0] not in remaining_racers]
        
        if not lap_times:
            continue  # If all racers are already eliminated, skip this lap
        
        # Sort by time (highest first) and alphabetically in case of ties
        lap_times.sort(key=lambda x: (-x[1], x[0]))

        # Get the slowest time from the sorted list
        slowest_time = lap_times[0][1]

        # Find all drivers with the slowest time
        slowest_drivers = [driver for driver, time in lap_times if time == slowest_time]
        
        # Sort slowest drivers alphabetically
        slowest_drivers.sort()

        # Add slowest drivers to the elimination list and update the set of eliminated racers
        for driver in slowest_drivers:
            if driver not in remaining_racers:
                eliminated.append(driver)
                remaining_racers.add(driver)

    return eliminated

laps = [
    ["Ivy 100","Kester 104","Kaan 121","Kirstin 135","Maegan 136"], 
    ["Kester 105","Kaan 119","Kirstin 141","Maegan 142","Ivy 149"], 
    ["Kirstin 100","Ivy 110","Maegan 132","Kaan 132","Kester 144"], 
    ["Kaan 106","Maegan 106","Kirstin 117","Kester 124","Ivy 126"], 
    ["Kester 106","Kirstin 108","Ivy 119","Kaan 124","Maegan 135"]
]

print(solution(laps))



['Maegan', 'Ivy', 'Kester', 'Kirstin', 'Kaan']


In [8]:
import numpy as np

list = [0,1,2,3,4,5,6,7,8,9]
list = np.array(list)
print((list>=5).astype(float))

[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]


In [10]:
from itertools import combinations
for i,j in combinations(range(4),2):
    print(i,j)

0 1
0 2
0 3
1 2
1 3
2 3


In [2]:
list = [3,6,8,3,2,1,6,8]


a=sorted(list)
print(a,list)
list.sort()
print(a,list)

[1, 2, 3, 3, 6, 6, 8, 8] [3, 6, 8, 3, 2, 1, 6, 8]
[1, 2, 3, 3, 6, 6, 8, 8] [1, 2, 3, 3, 6, 6, 8, 8]


In [ ]:
def solution(numbers):
    sol=[]
    for i in range(0,len(numbers)-2):
        if numbers[i]<numbers[i+1] and numbers[i+2]<numbers[i+1] or numbers[i]>numbers[i+1] and numbers[i+2]>numbers[i+1]:
            sol[i]=1
        else: 
            sol[i]=0
    return sol

In [23]:
def getMinOperations(kValues):
    
    # minOps = [0] * len(kValues)

    # print(kValues)

    # for i in kValues:
    #     x = int(i)
    #     # print(x) # each no needs +1 operation
    #     count = 0
    #     while x != 0:
    #         print(x)
    #         if x % 2 == 1: 
    #             x-=1
    #             count+=1
    #             if x == 0:
    #                 break
    #             print(x,count)
    #         x/=2
    #         count+=1
    #         print(x,count)
    #     minOps[kValues.index(i)]=count
    # return minOps

    def minOps(k):
        count = 0
        while k>0:
            if k % 2 == 0:
                k//=2
            else:
                k-=1
            count+=1
        return count
    
    return [minOps(k) for k in kValues]

if __name__ == "__main__":
    kValues=[]
    n = int(input("Enter size of kValue Array"))
    print("Enter the elements for kValues")
    for i in range(n):
        kValues.append(int(input()))

    print(getMinOperations(kValues))

Enter the elements for kValues
[4, 3]


In [21]:
a = 4

print(int(a//2))


2


In [ ]:
# List of fruits to be used in fruit salad
fruits = ['apple', 'banana', 'kiwi', 'mango']

# TODO: Loop over the list of fruits and add them to the fruit salad with a print statement
for fruit in fruits:
    # TODO: Print a statement for adding each fruit to the fruit salad.
    print(f"Adding {fruit} to the salad.")